=== braverokmc/cjh_git_egoing/XML/c4_1006.dtd
<?xml version="1.0" encoding="euc-kr"?>

<!ELEMENT  booklist (book*) >
    <!ELEMENT book (title , author+ , publisher) >
    <!ELEMENT title (#PCDATA) >
    <!ELEMENT author (#PCDATA) >
    <!ELEMENT publisher (#PCDATA) >

=== braverokmc/cjh_git_egoing/XML/c4_1006.xml
<?xml version="1.0" encoding="euc-kr"?>

<!-- 문서 유형 선언 -->

<!DOCTYPE booklist SYSTEM "c4_1006.dtd" >

<!-- 루트 엘리먼트 -->

<booklist>
    <book>
        <title>XML 기본서</title>
        <author>최준호</author>
        <author>홍길똥</author>
        <publisher>프리렉</publisher>
    </book>
    
    <book>
        <title></title>
        <author></author>
        <publisher></publisher>
    </book>
    
    
</booklist>
