=== braverokmc/cjh_git_egoing/XML/c6_1401.xsd
<?xml version="1.0" encoding="euc-kr"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    
    <xsd:element name="booklist" type="ctBooklist"/>
        
    
    <xsd:complexType name="ctBooklist">
        <xsd:sequence>
            <xsd:element name="book" type="ctBook" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>    
        
    <xsd:complexType name="ctBook">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="author" type="ctAuthor" />
            <xsd:element name="publisher" type="ctPublisher" />
        </xsd:sequence>
    </xsd:complexType>
    
    
    <xsd:complexType name="ctAuthor">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="tel" type="ctPhone"/>
        </xsd:sequence>
    </xsd:complexType>    
    
    <xsd:complexType name="ctPublisher">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" />
            <xsd:element name="phone" type="ctPhone" />
        </xsd:sequence>
    </xsd:complexType>
    
   
   
    <xsd:complexType name="ctPhone">
        <xsd:group ref="gTel"/>
        
    </xsd:complexType>
   
    <xsd:group name="gTel">
        <xsd:sequence>
            <xsd:element name="home" type="xsd:string" minOccurs="0" />
            <xsd:element name="office" type="xsd:string" minOccurs="0" />
            <xsd:element name="mobile" type="xsd:string" minOccurs="0" />
        </xsd:sequence>
    </xsd:group>
   
   
       
</xsd:schema>

=== braverokmc/cjh_git_egoing/XML/c6_1401.xml
<?xml version="1.0" encoding="euc-kr"?>

<booklist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="c6_1401.xsd">
    
    <book>
        <title>Visual Basic</title>
        <author>
            <name>최준호</name>
            <tel>
                <home>042-4234-234</home>
                <mobile>03424-4234-342</mobile>
            </tel>
        </author>
        <publisher>
            <name>프리렉</name>
            <phone>
                <office>45334</office>
            </phone>
        </publisher>
    
    </book>
    
    
    
    
</booklist>
