=== braverokmc/cjh_git_egoing/XML/c8_0701.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    
    <xsd:element name="booklist" >
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="book" type="ctBooklist"  maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:complexType name="ctBooklist" >
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string" />
            <xsd:element name="author" type="xsd:string" />
            <xsd:element name="publisher" type="xsd:string" />
            <xsd:element name="price" type="xsd:int" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:ID"  use="required" />
        <xsd:attribute name="kind" type="xsd:string" use="optional" default="computer"/>
        
    </xsd:complexType>
    
    
    
    
</xsd:schema>

=== braverokmc/cjh_git_egoing/XML/c8_0701.xml
<?xml version="1.0" encoding="euc-kr"?>

<!-- XSL 문서 적용 -->
<?xml-stylesheet type="text/xsl" href="c8_0802.xsl"?>

<booklist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="c8_0701.xsd">
   
    
    
    <book id="b1" kind="">
      <title>JSP And Serverlet</title>
      <author>이규민</author>
      <publisher>인포북</publisher>
      <price>25000</price>
  </book>
   
   
    <book id="b2" kind="computer">
       <title>Inside XML</title>
       <author>신민철</author>
       <publisher>디지털북스</publisher>
       <price>35000</price>
   </book>
   
   
   <book id="b3" kind="lnaguage">
       <title>쉽게 배우는 영어</title>
       <author>채규태</author>
       <publisher>시사영어사</publisher>
       <price>200000</price>
   </book>
   
   
   <book id="b4" kind="computer">
       <title>XML 전자상거래</title>
       <author>이종호</author>
       <publisher>정보문화사</publisher>
       <price>28000</price>
   </book>
    
    <book id="b5" kind="소설">
        <title>사랑과 전쟁</title>
        <author>이사랑</author>
        <publisher>전쟁문화사</publisher>
        <price>15000</price>
    </book>
    
    <book id="b6" kind="수필">
        <title>사랑을 느끼세요</title>
        <author>이사랑</author>
        <publisher>사랑출판사</publisher>
        <price>15000</price>
    </book>
    
    
    <book id="b7" kind="잡지">
        <title>월간 중앙</title>
        <author>중앙일보기사</author>
        <publisher>중앙일보사</publisher>
        <price>18000</price>
    </book>
    
    <book id="b8" kind="잡지">
        <title>주간 경제지</title>
        <author>조선일보기자</author>
        <publisher>조선일보사</publisher>
        <price>27000</price>
    </book>
    
    
    
</booklist>
